#!/bin/bash

# Parse command line args
if [ "$4" == "" ]; then
    echo "Invalid number of arguments."
    echo -e "\nCommand Syntax:"
    echo "command <display> <display_count> <height> <gaps>"
    echo -e "\nExample:"
    echo "command DP-1 2 30 10"
    exit
fi

display=$1
BARW=0
BARH=$3
RESX=0
POSX=0
GAPS=$4
DISPLAY_COUNT=$2

# Automatically get screen data from xrandr
SCREENDATA=$(xrandr | grep $display | sed 's/[^+]* \([^+]*[^ ]*\).*/\1/')
RESX=$(echo $SCREENDATA | sed 's/\([^x]*\).*/\1/')
POSX=$(($(echo $SCREENDATA | sed 's/[^+]*+\([^+]*\)+.*/\1/') + $GAPS))
BARW=$(($RESX - $GAPS * 2))

# Color Theme File
CTF="$HOME/.Xresources"

# Colors
BACKGROUND=$(cat ${CTF} | grep -ixe '*color0:.*' | tail -c 8)
BACKGROUND_LIGHT=$(cat ${CTF} | grep -ixe '*color8:.*' | tail -c 8)
FOREGROUND=$(cat ${CTF} | grep -ixe '*color7:.*' | tail -c 8)
FOREGROUND_LIGHT=$(cat ${CTF} | grep -ixe '*color15:.*' | tail -c 8)
HIGHLIGHT=$(cat ${CTF} | grep -ixe '*color1:.*' | tail -c 8)

# Shutdown popup
POW="$HOME/.config/panel/shutdown_popup"

ws() {
    WORKSPACE_ICONS=("    " "    " "    " "    " "    ")
    ACTIVE=$(i3-msg -t get_workspaces | sed 's/"num":\([^,]*\)[^{]*"visible":\([^,]*\)[^}]*},"output":"\([^"]*\)/\n\1*\2*\3\n/g'| grep "true\*"$display"" | sed 's/\([0-9]*\).*/\1/')
    ALL=$(i3-msg -t get_workspaces | sed 's/"num":\([^,]*\)[^{]*"visible":\([^,]*\)[^}]*},"output":"\([^"]*\)/\n\1*\2*\3\n/g' | grep "\*"$display"" | sed 's/\([^\*]*\).*/\1/' | sort -g)
    OUTPUT=""
    for i in $ALL; do
        ICON="${WORKSPACE_ICONS[$((($i - 1) / $DISPLAY_COUNT))]}"
	if [[ "$i" -eq "$ACTIVE" ]]; then
	    OUTPUT="$OUTPUT%{B$HIGHLIGHT}%{F$FOREGROUND_LIGHT}$ICON"
	else
	    OUTPUT="$OUTPUT%{B$BACKGROUND_LIGHT}%{F$FOREGROUND}$ICON"
	fi
    done
    OUTPUT="$OUTPUT%{B$BACKGROUND}%{F$FOREGROUND}"
    echo "$OUTPUT"
}

get_vol() {
    LEVEL=$(amixer -D pulse get Master | grep -o "\[.*%\]" | grep -o "[0-9]*" | head -n1)
    OUTPUT="   $LEVEL  "
    echo "$OUTPUT"
}

get_date() {
    DATE=$(date '+%A, %d. %B %H:%M')
    OUTPUT="  🕘 $DATE  "
    echo "$OUTPUT"
}

while :; do
	echo "%{B$BACKGROUND}%{F$HIGHLIGHT}%{A:$POW:}    %{A}%{B$BACKGROUND}%{F$FOREGROUND}$(ws)%{c}$(get_date)%{r}$(get_vol)"
    sleep .5
done | lemonbar -d -p -n "LMNBAR" -g ${BARW}x${BARH}+${POSX}+${GAPS} -F "$FOREGROUND" -B "$BACKGROUND" -f "Source Code Pro Semibold-12" -f "FontAwesome-15"
