#!/bin/bash

cp .zshrc ~/
cp .xinitrc ~/
cp .spacemacs ~/
cp compton.conf ~/.config/
cp termite/config ~/.config/termite/

cp -r i3/ ~/.config/
cp -r panel/ ~/.config/
cp -r Thunar/ ~/.config/
cp -r neofetch/ ~/.config/
cp -r powerline/ ~/.config/
echo "Please copy the usr/share/themes/Numix-Undead folder into /usr/share/themes/ with root permissions yourself."
echo "Please remember to setup the bar in your i3 config."
