#!/bin/bash

cp ~/.zshrc .
cp ~/.xinitrc .
cp ~/.spacemacs .
cp ~/.config/compton.conf .
cp ~/.config/termite/config ./termite/

cp -r ~/.config/i3 .
cp -r ~/.config/panel .
cp -r ~/.config/Thunar .
cp -r ~/.config/neofetch .
cp -r ~/.config/powerline .
cp -r /usr/share/themes/Numix-Undead ./usr/share/themes/
