alias vim="nvim"
alias sudo="sudo "
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias gp="git symbolic-ref --short HEAD 2> /dev/null | xargs -L1 git push origin"
alias ssh="TERM=xterm-256color ssh"
alias hs="homesec -e"
alias hsec="homesec"
