#!/bin/bash

if [[ "$1" == "" ]];then
	echo "Please specify a temperature limit as command line argument"
fi

TEMP_LIMIT=$1

TEMPS=$(sensors | sed 's/([^)]*)//' | grep °C | sed 's/.*+\([^.]*\).*/\1/' )
TMP=$'\r\n' GLOBIGNORE='*' command eval 'TEMPS_ARRAY=($TEMPS)'

while :; do
	for sensor_index in "${!TEMPS_ARRAY[@]}"; do
		if [[ "${TEMPS_ARRAY[$sensor_index]}" -gt "$TEMP_LIMIT" ]]; then
			warning_sent=$($HOME/Scripts/leechnot.py all | grep "Sensor "$sensor_index" temp alert" | wc -l)
			if [[ "$warning_sent" -eq 0 ]]; then
				app_name='Temperature Warning'
				notif_summary='Sensor '$sensor_index' temp alert.'
				notif_body='The maximum temperature of '$TEMP_LIMIT'°C has been exceeded! Temperature reported: '${TEMPS_ARRAY[$sensor_index]}'°C'
				$HOME/Scripts/leechnot.py send "$app_name" "$notif_summary" "$notif_body"
			fi
		fi
	done
	sleep 30
done
