# Load env variables
source ~/.config/zsh/env.zsh

# Launch SSH agent.
eval $(ssh-agent -t 3600)

# Automatically start Catacomb on tty1
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
    catacomb
fi
