# COMPLETION
autoload -U compinit && compinit                           # Autoload and start autocompletion

# Complete case-insensitive
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select                         # Highlight menu when cycling through
setopt MENU_COMPLETE                                       # Instantly complete first menu item

# HISTORY
HISTFILE=$HOME/.zsh_history                                # Set the path of the history file
SAVEHIST=100000                                            # Set size of history file
HISTSIZE=100000                                            # Set size of local history
setopt APPEND_HISTORY                                      # Allow multiple sessions with one history
setopt SHARE_HISTORY                                       # Update history live
setopt HIST_REDUCE_BLANKS                                  # Remove unnecessary blanks from history
setopt HIST_IGNORE_DUPS                                    # Ignore duplicates in history
setopt HIST_VERIFY                                         # Perform history expansion before add
setopt INC_APPEND_HISTORY                                  # Add to history upon entering command

# GLOBBING
setopt NO_CASE_GLOB                                        # Expand case-insensitive

# MISC
setopt AUTO_CD                                             # Without any command, execute `cd`

# KEYS
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '\e[A' up-line-or-beginning-search                 # [Up]         history search with input
bindkey '\e[B' down-line-or-beginning-search               # [Down]       history search with input

bindkey "^[[1;5C" forward-word                             # [Ctrl-Right] move forward one word
bindkey '^[[1;5D' backward-word                            # [Ctrl-Left]  move backward one word

# LS/COMPLETION COLORS
export LS_COLORS='ow=36:di=34:fi=32:ex=31:ln=35:'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:*:*:*' menu yes select

# ENV
export PATH=$HOME/.cargo/bin:$HOME/bin:/usr/local/bin:$HOME/Scripts:$PATH
export EDITOR="nvim"
export VISUAL="nvim"

# RUST ENV
export RLS_ROOT=$HOME/.cargo/bin/rls
export LD_LIBRARY_PATH=$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
export RUST_SRC_PATH=$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src

# Colorized Manpages
man() {
    env \
        LESS_TERMCAP_md=$'\e[32m' \
        LESS_TERMCAP_me=$'\e[0m' \
        LESS_TERMCAP_se=$'\e[0m' \
        LESS_TERMCAP_so=$'\e[100;37m' \
        LESS_TERMCAP_ue=$'\e[0m' \
        LESS_TERMCAP_us=$'\e[34m' \
            man "$@"
}

# ALIAS
alias vim="nvim"
alias sudo="sudo "
alias ls="ls --color"
alias grep="grep --color"
alias gp="git remote | xargs -L1 git push --all"

# AUTOSUGGESTIONS
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# PROMPT
POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_HIDE_BRANCH_ICON=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon background_jobs virtualenv dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

POWERLEVEL9K_HOME_ICON=""
POWERLEVEL9K_FOLDER_ICON=""
POWERLEVEL9K_HOME_SUB_ICON=""
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=" "

shorten_username() {
    if [[ "$USER" == "root" ]]; then; echo "R"; else; echo "UL"; fi
}
POWERLEVEL9K_LINUX_ICON=$(shorten_username)
POWERLEVEL9K_OS_ICON_BACKGROUND="009"
POWERLEVEL9K_OS_ICON_FOREGROUND="000"

POWERLEVEL9K_VCS_CLEAN_BACKGROUND="002"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="000"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="009"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="000"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="004"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="000"

POWERLEVEL9K_VIRTUALENV_BACKGROUND="008"
POWERLEVEL9K_VIRTUALENV_FOREGROUND="007"

POWERLEVEL9K_DIR_HOME_BACKGROUND="008"
POWERLEVEL9K_DIR_HOME_FOREGROUND="007"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="008"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="007"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="008"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="007"

POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="008"
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="007"

autoload -U colors && colors
source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme
