# Load prompt
source ~/.config/zsh/powerlevel9k.zsh

# Load shell aliases
source ~/.config/zsh/alias.zsh

# Load keyboard shortcuts
source ~/.config/zsh/keys.zsh

# Load zsh options
source ~/.config/zsh/setopt.zsh

# Autosuggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Powerlevel9K
source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme

# Completion and ls colors
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:*:*:*' menu yes select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select

# Autoload functions
autoload -U compinit && compinit
autoload -U colors && colors
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
