# Load prompt
source ~/.config/zsh/ps1.zsh

# Load shell aliases
source ~/.config/zsh/alias.zsh

# Load keyboard shortcuts
source ~/.config/zsh/keys.zsh

# Load zsh options
source ~/.config/zsh/setopt.zsh

# Autosuggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Completion and ls colors
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:*:*:*' menu yes select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select

# Autoload functions
autoload -U compinit && compinit
autoload -U colors && colors
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Set TTY for GPG for each instance
export GPG_TTY=$(tty)

# Prevent Ctr-S from locking up the terminal
$exec stty -ixon
