---
outlines:
    default: { width: 35.33, height: 52 }
    wide: { width: 52.67, height: 52 }
    spaceline: { width: 177.33, height: 52 }
views:
    base:
        - "q w e r t y u i o p"
        - "↹ a s d f g h j k l"
        - "Shift_L   z x c v b n m  BackSpace"
        - "show_numbers /         space        . Return"
    upper:
        - "Q W E R T Y U I O P"
        - "A S D F G H J K L"
        - "Shift_L   Z X C V B N M  BackSpace"
        - "show_numbers /         space        . Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0"
        - "@ # $ % & - _ + ( )"
        - "show_symbols   , \" ' colon ; ! ?  BackSpace"
        - "show_letters /         space        . Return"
    symbols:
        - "~ ` | · √ π τ ÷ × ¶"
        - "© ® £ € ¥ ^ ° * { }"
        - "show_numbers_from_symbols   \\ / < > = [ ]  BackSpace"
        - "show_letters /         space        . Return"
buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "wide"
        icon: "key-shift"
    BackSpace:
        outline: "wide"
        icon: "edit-clear-symbolic"
        action: erase
    show_numbers:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "wide"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "wide"
        label: "*/="
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "wide"
        icon: "key-enter"
        keysym: "Return"
    colon:
        text: ":"
    ↹:
        outline: "action"
        keysym: "Tab"
